name: Rust Format & Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    branches: [main, development]

jobs:
  format-and-test:
    name: Run Rust Tests
    if: "! github.event.pull_request.draft"
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Format
        run: cargo +nightly fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Run Tests
        run: |
          cp .env-example .env
          cargo test --all-features
